name: secure_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  shelf: ^1.3.0
  web_socket_channel: ^2.1.0
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  network_info_plus: ^2.1.3
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  isar_generator: ^2.2.1
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #         style: italic
